name: Run watir-rails CI

'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby-version == 'debug' }}
    strategy:
      matrix:
        rails-version: ['3.2', '4.2', '6.0']
        ruby-version: ['2.6.3', 'debug']
        exclude:
          # rails-4.2 requires BigDecimal.new (dropped in ruby-2.7)
          - { rails-version: '4.2', ruby-version: 'debug' }
          # The issue on rails-3.2 + head is json-1.8.6 compat (simplecov
          # uses it), we could potentially workaround it using, for example, Oj
          - { rails-version: '3.2', ruby-version: 'debug' }
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails-version }}.gemfile

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          # rails < 5 doesn't support bundler-2
          bundler: 1
          bundler-cache: true

      - run: bundle exec rake

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage/lcov.info'
          parallel: true
          flag-name: ruby-${{ matrix.ruby-version }}_rails-${{ matrix.rails-version }}

  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
